package com.pinyougou.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbAddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.user_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.province_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.city_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.town_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String townId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.mobile
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.address
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.contact
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.is_default
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.notes
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.create_date
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.alias
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    private String alias;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.id
     *
     * @return the value of tb_address.id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.id
     *
     * @param id the value for tb_address.id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.user_id
     *
     * @return the value of tb_address.user_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.user_id
     *
     * @param userId the value for tb_address.user_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.province_id
     *
     * @return the value of tb_address.province_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.province_id
     *
     * @param provinceId the value for tb_address.province_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.city_id
     *
     * @return the value of tb_address.city_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.city_id
     *
     * @param cityId the value for tb_address.city_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.town_id
     *
     * @return the value of tb_address.town_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getTownId() {
        return townId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.town_id
     *
     * @param townId the value for tb_address.town_id
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setTownId(String townId) {
        this.townId = townId == null ? null : townId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.mobile
     *
     * @return the value of tb_address.mobile
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.mobile
     *
     * @param mobile the value for tb_address.mobile
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.address
     *
     * @return the value of tb_address.address
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.address
     *
     * @param address the value for tb_address.address
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.contact
     *
     * @return the value of tb_address.contact
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.contact
     *
     * @param contact the value for tb_address.contact
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.is_default
     *
     * @return the value of tb_address.is_default
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.is_default
     *
     * @param isDefault the value for tb_address.is_default
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.notes
     *
     * @return the value of tb_address.notes
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.notes
     *
     * @param notes the value for tb_address.notes
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.create_date
     *
     * @return the value of tb_address.create_date
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.create_date
     *
     * @param createDate the value for tb_address.create_date
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.alias
     *
     * @return the value of tb_address.alias
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.alias
     *
     * @param alias the value for tb_address.alias
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }
}