package com.pinyougou.mapper;

import com.pinyougou.pojo.TbSeckillGoods;
import com.pinyougou.pojo.TbSeckillGoodsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbSeckillGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int countByExample(TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int deleteByExample(TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int insert(TbSeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int insertSelective(TbSeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    List<TbSeckillGoods> selectByExample(TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    TbSeckillGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbSeckillGoods record, @Param("example") TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int updateByExample(@Param("record") TbSeckillGoods record, @Param("example") TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int updateByPrimaryKeySelective(TbSeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Sat Mar 02 16:57:17 CST 2019
     */
    int updateByPrimaryKey(TbSeckillGoods record);
}